version: '3'
services:
  pebble:
    image: letsencrypt/pebble:latest
    command: pebble -config /test/config/pebble-config.json -strict -dnsserver challtestsrv:8053
    # ports:
    #   - "14000:14000"  # HTTPS ACME API
    #   - "15000:15000"  # HTTPS Management API
  challtestsrv:
    image: letsencrypt/pebble-challtestsrv:latest
    depends_on:
      - pebble
    command: pebble-challtestsrv -http01 "" -tlsalpn01 "" -dns01 ":8053"
    ports:
      - "8055:8055"      # HTTP Management API
      - "8053:8053/tcp"  # DNS API
      - "8053:8053/udp"  # DNS API
  vault:
    image: vault:1.6.2
    # ports:
    #   - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=supersecret
  app:
    build: .
    depends_on:
      - pebble
      - challtestsrv
      - vault
    env_file:
      - .env.dev

  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    depends_on:
      - pebble
      - challtestsrv
      - vault
    command: ["true"] # do not start the container when `docker-compose up` is executed
